### ISSUE TITLE
Test::Kit integration

### ISSUE THREAD

**Issue by Ovid** [test-class-moose/test-class-moose#37]
When I wrote `Test::Class::Moose`, I made a design decision that I currently regret. Specifically, `Test::Most` is automatically provided. However, it's showing its age. `Test::Kit` would have been a better choice, but I had never gotten around to fixing some core issues in the latter.

Recently, Alex Balhatchet has taken over `Test::Kit` and [it's now a much more flexible testing system](http://search.cpan.org/dist/Test-Kit/lib/Test/Kit.pm). By determining how to combine the two, we can offer users the power of `Test::Class::Moose`, but using a set of their own test modules rather than whatever I thought to include in `Test::Most`.

**Comment by autarch** [comment]
I'm inclined to close this.

With the `bare => 1` option, people can use whatever test modules they like. Personally, I'm moving towards using `Test2::Bundle::Extended` in new code.

I also note that you can provide your own in-house TCM style by doing something like this:

```
package My::Test::Class::Moose;

use Import::Into;
use Test::Class::Moose ();

sub import {
    Test::Class::Moose->import::into( 1, bare => 1 );
    Test2::Bundle::Extended->import::into(1);
    namespace::autoclean->import::into($caller_level);
    # More stuff here if you like
}
```

**Comment by Ovid** [comment]
That sounds quite reasonable to me.
