### ISSUE TITLE
Broken Link at top of documentation

### ISSUE THREAD

**Issue by 2shortplanks** [test-class-moose/test-class-moose#46]
Test::Class::Moose home page isn't at http://ovid.github.io/test-class-moose/ - that gives a 404

**Comment by autarch** [comment]
Fixed in 0.59, thanks.

**Comment by abraxxa** [comment]
The link is broken again and returns a github 404 page.

**Comment by autarch** [comment]
This is fixed in the repo. I'll do a release soon.

**Comment by abraxxa** [comment]
Thanks Dave!
