### ISSUE TITLE
reportpassed.t fails with old Moose

### ISSUE THREAD

**Issue by chorny** [test-class-moose/test-class-moose#48]
http://www.cpantesters.org/cpan/report/ca4c9b7f-6bfe-1014-b3ae-b8b5afa91a94

Fails with Moose 2.1005 or earlier. Does not fail with 2.1201 or newer. Checked myself and used http://analysis.cpantesters.org/solved?distv=Test-Class-Moose-0.58

**Comment by Ovid** [comment]
This is fixed in #00efc04
