### ISSUE TITLE
Can't access name of "run" from within class

### ISSUE THREAD

**Issue by 2shortplanks** [test-class-moose/test-class-moose#51]
Test::Class::Moose doesn't expose the internal name of a run to the run instance itself.

I'm working on a role that creates named directories for each test run.  For classes that have a one-to-one mapping of class to run this is trivial, but at for classes that produce multiple runs per class file (e.g. parameterized classes) I can't get a unique name for the test run because TCM doesn't expose the internal name it uses.

**Comment by autarch** [comment]
I just realized this already exists but isn't documented:

    $self->test_report->current_class->name

But I need to rename `current_class` to `current_instance`.

**Comment by autarch** [comment]
Fixed in 0.61
