### ISSUE TITLE
Can't locate object method "_tcm_make_test_class_instances" and/or skipped tests

### ISSUE THREAD

**Issue by andycunningham** [test-class-moose/test-class-moose#57]
Hi

I'm working on a team which is developing a Moose based app which uses Test::Class::Moose as the testing framework. We're seeing a very generic error message returned, or in some cases skipped tests completely, if there is a syntax error in the test class and/or file being tested. After speaking to @Ovid, raising here as an issue here.

The replication steps below may not be exhaustive but hopefully highlight the issues.
### Can't locate object method "_tcm_make_test_class_instances"

This occurs when there is a compilation error in the test file itself, in this case a missing semi-colon in the test class file.

```
t/20-units/run_class.t ..
1..1
#
# Running tests for Test::XXX
#
    # Subtest: Test::XXX
Can't locate object method "_tcm_make_test_class_instances" via package "Test::XXX" (perhaps you forgot to load "Test::XXX"?) at /opt/xt/xt-perl/lib/site_perl/Test/Class/Moose/Role/Executor.pm line 52.
END failed--call queue aborted.
# Looks like your test exited with 22 before it could output anything.
Dubious, test returned 22 (wstat 5632, 0x1600)
Failed 1/1 subtests

Test Summary Report
-------------------
t/20-units/run_class.t (Wstat: 5632 Tests: 0 Failed: 0)
  Non-zero exit status: 22
  Parse errors: Bad plan.  You planned 1 tests but ran 0.
Files=1, Tests=0,  5 wallclock secs ( 0.03 usr  0.01 sys +  4.81 cusr  0.16 csys =  5.01 CPU)
Result: FAIL
```
### Skipped tests (no test methods found)

The second issue occurs when there is a syntax issue with the file being tested, in this case a missing semi-colon. This one is problematic as the tests come back as PASS and if you aren't running in verbose mode if can be easily overlooked.

```
t/20-units/run_class.t ..
1..1
#
# Running tests for Test::XXX
#
    # Subtest: Test::XXX
    1..0 # SKIP Skipping 'Test::XXX': no test methods found
ok 1 # skip Skipping 'Test::XXX': no test methods found
# Test instances:  1
# Test methods:    0
# Total tests run: 0
ok
All tests successful.
Files=1, Tests=1,  3 wallclock secs ( 0.03 usr  0.01 sys +  2.27 cusr  0.23 csys =  2.54 CPU)
Result: PASS
```

If you need anymore information just let me know.

Attaching @Ovid's quote for reference:

> The issue you're describing came up when TCM was refactored to allow instances of test classes (allowing you to run a test class in different contexts) and I've seen in a couple of times myself. I keep forgetting to resolve it. I suspect it's an unchecked eval. Could you open an issue in our repo so both Dave and I are notified?

Thanks

Andy

**Comment by autarch** [comment]
This definitely sounds like a bug. If we load a module and it contains an error then that should not be hidden.

I suspect the best option would be to emit a single failing test for the class as a whole.

I'm not following the distinction between the two cases you describe, however. What is " the test file itself" versus "the file being tested"? Could you use more concrete names?

**Comment by autarch** [comment]
Even better, can you make a PR with some files that fail in these various ways? You don't need to fix the problem, I just need some test cases.

**Comment by andycunningham** [comment]
Sure, I'll put together a test case which hopefully demonstrates this.

**Comment by andycunningham** [comment]
I've had trouble coming up with test cases for this as putting together new test cases with syntax errors (which is what causes this behavior in our repo) doesn't for these new tests. It suggests there is something in particular we are doing in our code which is causing this to happen, which will involve unpicking our code. @Ovid did mention he had seen this before however. I'll keep chipping away and if I come up with a test case(s) I'll pop them in a PR.

**Comment by hoppfrosch** [comment]
Any chance to get this unstalled anytime soon?
I'm refactoring my quite large perl package - I just moved all my tests from Test::Able to Test::Class::Moose, which worked quite easy - and all Unittests worked then. Now I'm trying rename all my packages by adding an additional hierarchy level (renaming from B::C::D to A::B::C::D). After renaming the files and doing all the related changes suddenly the described error occurs: ""Can't locate object method "_tcm_make_test_class_instances"" with all my Unittest-Modules.
Now all my tests do not work anymore - and I cannot test my software anymore (which is really bad, as I rely on the Unittests before publishing) ...

**Comment by autarch** [comment]
It's stalled because there's no reproduction recipe. If you can provide a failing test I can look into it.

**Comment by hoppfrosch** [comment]
Unfortunately I don't have a reprocuction recipe either - I'll keep my heads up, unless  I'm not forced to abandon Test::Class::Moose to get working UnitTests again :-/

**Comment by Ovid** [comment]
The only way I can replicate this is to *not* use `Test::Class::Moose::Load` and thus fail to load the tests in question. 

```perl
# t/tcm.t
#!/usr/bin/env perl
use Test::Class::Moose::Runner;

# XXX commenting out the two following lines will show the error message in question
#use Test::Class::Moose::Load;
#Test::Class::Moose::Load->import('t/tests');
my $runner = Test::Class::Moose::Runner->new(
    test_classes => ['TestsFor::Foo'],
);
$runner->runtests;
```

And the test class:

```perl
package TestsFor::Foo;

use Test::Class::Moose;

sub test_me {
    ok 1, 'this test should pass';
}

1;
```

Running `prove t/tcm.t` will produce:

```
t/tcm.t .. 
1..1
# 
# Running tests for TestsFor::Foo
# 
# Subtest: TestsFor::Foo
    1..0
    # No tests run!
not ok 1 - No tests run for subtest "TestsFor::Foo"

#   Failed test 'No tests run for subtest "TestsFor::Foo"'
#   at /Users/curtispoe/perl5/perlbrew/perls/perl-5.24.0/lib/site_perl/5.24.0/darwin-2level/Moose/Meta/Method/Delegation.pm line 110.
Can't locate object method "_tcm_make_test_class_instances" via package "TestsFor::Foo" (perhaps you forgot to load "TestsFor::Foo"?) at /Users/curtispoe/perl5/perlbrew/perls/perl-5.24.0/lib/site_perl/5.24.0/Test/Class/Moose/Executor/Sequential.pm line 56.
# Looks like your test exited with 255 just after 1.
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests 

Test Summary Report
-------------------
t/tcm.t (Wstat: 65280 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 255
Files=1, Tests=1,  1 wallclock secs ( 0.02 usr  0.01 sys +  0.34 cusr  0.02 csys =  0.39 CPU)
Result: FAIL
```

**Comment by autarch** [comment]
Ah, that makes sense. It'd be nice to give a better error message. We could check that the class has this method (and maybe isa TCM). If it's not, we can give a nice error message about the class probably not being loaded.

**Comment by Ovid** [comment]
I suspect it may not quite be the problem, though, as the issue in question is the test class having a syntax error but the above error message masking the issue. Still, it seems related, as either way the test class is not loaded.

**Comment by hoppfrosch** [comment]
ATM the problem seems gone again (after updating serveral Perl Modules and sorting out some problems with simultaneously active cygwin environment of WinPython (beside the Strawberry-Perl cygwin env...))

**Comment by hoppfrosch** [comment]
I found a reproducable reason for the occurance if this error (at least at my machine):

As I'm on a Windows-OS Uppercase/lowercase is not really considered. But Test::Class::Moose runs into problems with Upper/Lowercase names (which is correct IMHO).

I used for example accidently the following notation:

For the Moose packagename: **A:B:Cde**   ->  Filename **A/B/Cde.pm**
For the Moose Testclass: **TestsFor::A::B::CDE**  => Filename **TestsFor/A/B/CDE.pm**

Having the above case, the "Can't locate object method "_tcm_make_test_class_instances""-problem occurs. After homogenization the notation/letter-casing the problem disappears.

Maybe a more expressive error message could be provided in this case.
