### ISSUE TITLE
Passing report to test methods should be deprecated

### ISSUE THREAD

**Issue by Ovid** [test-class-moose/test-class-moose#63]
I really want to use sub signatures with tcm, but it's ugly having to account for the little-used `$report` variable passed to method (especially since that's available via `$test->report`. It would be nice if we deprecated passing that (if we haven't already) and schedule it for removal.

**Comment by autarch** [comment]
I can include this with the Test2 release (which I'm hoping to do in the next few weeks). Adding a doc notice is pretty trivial, obviously.
